
version: '3'

# --------------------------- Keycloak ------------------------

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: keycloak-db
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak-server
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgres

# --------------------------- Keycloak End ------------------------


  # --------------------------- task db ------------------------

  db:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_USER: my_user
      POSTGRES_DB: task_db


    ports:
      - '33008:5432'


    volumes:
      - my-db:/var/lib/pos

  # --------------------------- task db End ------------------------

