


spring:

    #    To specify the profile
  profiles:
    active: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888


#greeting: "Hello Local!"


# we need to enable the refresh endpoint
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

  endpoint:
    prometheus:
      enabled: true
