server:
  port: 9001


spring:
  main:
    web-application-type: reactive
  application:

    name: "gateway-service"


eureka:
  client:
    serviceUrl:
#          defaultZone: http://localhost:8761/eureka/
          defaultZone: http://eureka-us:9003/eureka/,http://eureka-jp:9002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"


  endpoint:
    gateway:
      enabled: true



#ribbon:
#  eureka:
#    enabled: false
#
#inventory-service:
#  ribbon:
#    listOfServers: http://eureka-us:8003/eureka/,http://eureka-jp:9006/eureka/