

#greeting: "hello local"


spring:
  application:
    name: eureka-server
    #    To specify the profile
  profiles:
    active: eureka
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888


#greeting: "Hello Local!"


# we need to enable the refresh endpoint
management:
  endpoints:
    web:
      exposure:
        include: refresh

#spring:
#  application:
#    name: microservice_mini_project
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  instance:
#    hostname: localhost
#server:
#  port: 8761


